### ISSUE TITLE
Carlos Review Summary

### ISSUE THREAD

**Issue by cdgomezo** [teokem/project-work-2021-MaxLindberg#2]
Hi @MaxLindberg , let's start with the checklist:

Documentation:
- [x] title and abstract of the project (max 300 words)
- [x] includes instructions on how to run the notebook
- [x] includes the required packages in an environment.yml file
- [x] includes a brief explanation of the reason each package/library was used
- [ ] includes rich documentation using Markdown (equations, tables, links, images or videos)
- [x] is reproducible, i.e., someone else should be able to redo the steps
 Input/Output:
- [x] uses pandas to read large data sets or numpy to load data from text files
- [x] uses pandas to save to disk the processed or generated data
 Scientific computing/data processing:
- [x] performs numerical operations (numpy, scipy, pandas) or manipulates, groups, and aggregates a data set (pandas)
 Data visualization:
- [x] includes at least one composite plot (inset or multiple panels)
- [ ] produces publication ready quality figures (see here for an editorial guide on Graphical Excellence):
- [x] the figures are 89 mm wide (single column) or 183 mm wide (double column)
- [x] the axes are labeled
- [x] the font sizes are sufficiently large
- [x] the figures are saved as rasterized images (300 dpi) or vector art
 Version control, sharing, and archiving:
- [x] is archived in a repository with a digital object identifier (DOI)

Now, some comments about your notebook. Your research topic is really interesting and you are offering such good tools for people working on similar topics to do these recurrent data analysis tasks.

Documentation:
I think you need a better explanation of what your notebook does. And you can easily do this by explaining in markdown cells your function `ratio_maker2`. I know it could be quite a tedious task to do, but you already have well commented on your function. So, my recommendation is to put this big function in a separate `*.py` file, then import it in the notebook as a package, and finally, explain what it does with markdowns. The same happens with other cells below where you have comments inside the code but maybe this is not sufficiently clear for the purpose of the notebook. Finally, you should reconsider if it is necessary to print some datasets and tables, maybe for some cases, you should just print some elements as an example and then explain what you are printing.

Data visualization:
In both plots, the error lines get overlapped with the annotations. Here are some nice examples from the `matplotlib` documentation: https://matplotlib.org/stable/gallery/lines_bars_and_markers/bar_label_demo.html#sphx-glr-gallery-lines-bars-and-markers-bar-label-demo-py
In the first figure, you can rotate a little bit the tick labels to improve the appearance of the figure using: `ax.tick_params(axis='x', which='both', labelbottom=True, labelrotation=40)`. Since you have some common names in the ticks, you can also group the bars. By doing this you have shorter and non-redundant names. You can use legend as well. Here some documentation: https://matplotlib.org/stable/gallery/lines_bars_and_markers/barchart.html#sphx-glr-gallery-lines-bars-and-markers-barchart-py
Finally, in the last figure, you should change the color of the bars to make visible the error bars. 

Cheers,
Carlos

**Comment by MaxLindberg** [comment]
Thank you for the good feedback! I think I have fixed everything now except importing the functions as *.py files, which I don't think is suitable for the purposes of this notebook (hopefully others in my group will use it and then they want to know exactly what that function does and probably change it every now and then).
