### ISSUE TITLE
Peer-review from teacher (replacing review from Daniel Coral)

### ISSUE THREAD

**Issue by caterina-doglioni** [teokem/project-work-2021-MaxLindberg#3]
Dear Max, 

Daniel Coral did not manage to submit a review so I'm filling in here. I like the fact that you had dev mode as an option - it's useful to have more outputs sometimes!

My suggestions are the following:

1. I would expand a bit on the cells of ## Generate new multi index and below, on what you want to achieve with each of the cells. There are a few technical terms (e.g. a 384 plate (A1 to P24)) and the reader not from your field would benefit from understanding why you use them and why they're important. 

2. I would add some more explanations of the conclusions you draw from the plots 

3. Instead of a "Done" cell I would add a Conclusions cell, a bit like in the conclusions of a paper, where you summarise what the user has learned from this Jupyter notebook. 

Thanks!
Caterina

**Comment by MaxLindberg** [comment]
Thank you for the feedback! I think I have implemented it all now.
